fileVersion: 1
id: ae87eb7b-bd82-1a32-b659-c2e44fe54205
name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 379e17ad-d77a-093a-62840a83f447
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: number(9)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATION_FUNCTION_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 8bab216c-681b-4e1d-9bd6-0d9fd2ae3678
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: cc771a01-c156-25bc-c10b99034ba8
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config:
          is_hd: true
        dataType: number(9)
        defaultValue: ""
        description: ""
        name: FUNCTION_TYPE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5e080a55-4019-47c7-8018-a384dead6635
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c133775b-a0bd-6913-5cde57afc84d
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config:
          is_hd: true
        dataType: varchar(50)
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_BY_USER
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 522825e7-1637-4499-9c73-23a3a2725e3e
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7565888b-3719-0ab2-6d039f4abed4
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config:
          is_hd: true
        dataType: timestamp
        defaultValue: ""
        description: ""
        name: LAST_MODIFIED_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 5a00cd22-fe39-413e-bad4-80a9958b0032
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 9e8eaf11-bc06-162e-bbbe3c40e59d
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config:
          is_hd: true
        dataType: number(9)
        defaultValue: ""
        description: ""
        name: USER_GROUP_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c0b434a6-2bf0-4cc7-98ab-76a03efaa18a
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0b7e2206-cd4e-4f73-9500-749d0bc1724f
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 768d8912-3f04-44dd-a18d-316e464935be
                stepCounter: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: ae87eb7b-bd82-1a32-b659-c2e44fe54205
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_MOSAIC_CDM_APPLICATION_FUNCTION: 049eeb7b-0467-4c93-8a5d-0a4fd0e9f377
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_MOSAIC_CDM_APPLICATION_FUNCTION
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_MOSAIC_CDM_APPLICATION_FUNCTION') }} "LOAD_MOSAIC_CDM_APPLICATION_FUNCTION "
        name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
        noLinkRefs: []
  name: ODS_MOSAIC_CDM_APPLICATION_FUNCTION
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
