fileVersion: 1
id: bd84ae4f-659f-ba03-b8a7-569b3f392715
name: ODS_XSPOC_TBLUSERSECURITY
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 27087b32-ade8-28ed-d652d45461b2
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: varchar(100)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: USERNAME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 2cf0f461-c71f-4a64-ace0-7620fedf383a
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d99a0bbd-b4d6-d5b8-67aa68ca64ce
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: WELLCONTROL
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 29b5abce-490a-4dbb-9bd2-571e359751f7
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 39bf3f3d-ee9a-f0da-0999b7140aee
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d4b497d6-3e3e-42dc-b594-f2bd36416942
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 73acd9a5-30b7-5066-c82595a1fae3
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: ADMIN
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 821d4d20-ae7f-40ac-9b48-1c0e8f0c0527
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 9c0da5fd-59db-4d46-63d3b917c26d
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: ADMINLITE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 0dec9cd8-0a99-4d9f-b2d3-678c35c6ea3c
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 874f0a03-9d9a-e3c6-ddcbd2d7e98b
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: WELLADMIN
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 40390bb4-869a-4e01-88e8-6b8e4499e09d
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ae4757e6-7ff6-d69a-0aba6bb107cd
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: WELLCONFIGLITE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ce1b4734-a651-4f45-ba25-9eb870af2016
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 319f4d26-36b5-dd87-1bb2c52e3178
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(50)
        defaultValue: ""
        description: ""
        name: PASSWORD
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d608d1ef-6982-49c9-b89f-26870a6d35b9
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 61a649a3-69e5-e35f-bb7aff3a80d9
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(100)
        defaultValue: ""
        description: ""
        name: EMAIL
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 419ad226-6cda-46f9-9223-a04a49aed376
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7b22e126-f53b-0790-0d89c42e53e5
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: timestamp
        defaultValue: ""
        description: ""
        name: LASTACCESSDATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e1d54b1f-d0b3-44be-a10b-5a43213ed68c
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 15110aae-1eb2-9be1-d6038c107049
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(36)
        defaultValue: ""
        description: ""
        name: WEBTOKEN
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c85ad40d-bc32-4514-9059-b743d2a71778
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: eeb8d6b6-89fa-f821-126580bc5adb
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: timestamp
        defaultValue: ""
        description: ""
        name: WEBTOKENEXPIRE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 107840f3-4950-4506-ae0e-c4f8da61421e
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 21b2b89b-140a-a2bd-c87ba4610f94
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: MUSTCHANGEPASSWORD
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a28ee8be-1b7b-4c41-99db-d4d2d58412cd
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e673b98e-339f-4288-a726-be7b6e6b084f
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 177ef1db-74ac-4e9c-8a71-672ee6f5c015
                stepCounter: ac7972dd-049a-48d7-9a32-e49e874ae4d0
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: bd84ae4f-659f-ba03-b8a7-569b3f392715
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLUSERSECURITY: ac7972dd-049a-48d7-9a32-e49e874ae4d0
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_XSPOC_TBLUSERSECURITY
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_XSPOC_TBLUSERSECURITY') }} "LOAD_XSPOC_TBLUSERSECURITY"
        name: ODS_XSPOC_TBLUSERSECURITY
        noLinkRefs: []
  name: ODS_XSPOC_TBLUSERSECURITY
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
