fileVersion: 1
id: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
name: ODS_XSPOC_TBLIPRWELLCONFIG
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d8b0281f-877e-859c-7838d5e559e4
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: varchar(50)
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: NODEID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3d39facf-4bea-4542-9bf9-5fb9a05cdfd5
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 281ed8f9-fe59-f1b8-6fd028a8f9ad
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: TESTDATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d175909b-6596-46a9-a7bb-7b2f6e4c5759
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b0813c6f-9722-7bf8-9f52c1bf09df
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: ANALYSISCORRELATIONID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: ad9234e0-951d-46de-96f2-68165f5b7881
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: aa815619-91a8-9edb-311e7ee6dcfe
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: FBHPANALYSISSOURCEID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: d7e6d1a4-f803-4fdb-bb91-e691882dbd99
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: aaaae26f-64db-8714-18d1495c1e44
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: GROSSRATEANALYSISSOURCEID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 3db821ba-d9c1-4086-ba9a-73eaa3e7907d
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: cc7781b9-c68c-ba81-950318dc424e
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: WATERCUTANALYSISSOURCEID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 32e71008-ae8f-4b74-915e-988f85c99f98
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1cd6d851-57b0-42ed-834a-a4ea79930401
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a6816c10-91e7-4739-8cb8-cdaf32f05ba9
                stepCounter: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: 4cc5b57a-20ca-8fe8-c8e5-cab929e807e6
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLIPRWELLCONFIG: 3e9dfeb2-13b0-4ea3-8638-ce630f95bfc6
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_XSPOC_TBLIPRWELLCONFIG
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_XSPOC_TBLIPRWELLCONFIG') }} "LOAD_XSPOC_TBLIPRWELLCONFIG"
        name: ODS_XSPOC_TBLIPRWELLCONFIG
        noLinkRefs: []
  name: ODS_XSPOC_TBLIPRWELLCONFIG
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
