fileVersion: 1
id: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 0c0f9989-9cb0-d8bb-e8f60914aa13
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: number
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: POCTYPE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 77d96152-3d60-4b11-9966-93243ed45702
                stepCounter: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 07a381b7-aaf3-4b34-ba4a84109a81
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: number
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: APPLICATIONID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6b5510ee-e3d6-4287-a97a-2a6f5efe4fff
                stepCounter: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 64644f92-21d0-31ae-e8707714fe41
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config:
          is_hd: true
        dataType: varchar(20)
        defaultValue: ""
        description: ""
        name: ISDEFAULT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c71ebddc-9cc0-44d3-bec2-23e75ce4d0ad
                stepCounter: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c4a34b81-ed5c-45aa-8608-4c04359063a8
                stepCounter: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 06bbdad2-59d4-4818-b55f-e46da6151878
                stepCounter: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: 8c4fc776-02d4-aea9-0dac-a11eb59c16aa
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS: 3746c0b6-d6f5-4c46-89a6-e96920e202cb
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS') }} "LOAD_XSPOC_TBLPOCTYPEAPPLICATIONS"
        name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
        noLinkRefs: []
  name: ODS_XSPOC_TBLPOCTYPEAPPLICATIONS
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
