fileVersion: 1
id: 0de55244-3012-40ee-5102-40f41f2aa5f0
name: ODS_XSPOC_TBLMOTORSETTINGS
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 752c9164-b475-8492-9a9bf5ff0991
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: number
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: MOTORSETTINGID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 30a00222-8214-44fd-af18-eea497c280f4
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: ad32e604-67fc-4355-38334fbddf3e
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: varchar(255)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 54b5c691-4af8-4a7f-a20a-63bddde3f643
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 3cf6eb33-11df-d501-b98a048685d2
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: float
        defaultValue: ""
        description: ""
        name: FULLLOADRPM
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 1b72a4d6-f9a7-4338-9d99-4c12e01cc6eb
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c9d689df-8aa8-febc-49ca950e938f
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: float
        defaultValue: ""
        description: ""
        name: MAXLOAD
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a8ab6d10-b06a-4579-ab61-88427f4721e9
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 3e59ad18-6152-832c-13536511571a
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: float
        defaultValue: ""
        description: ""
        name: MAXSPV
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 43cbe183-a413-4d34-802b-7a0977d509ce
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: d547baa2-a37b-9e9d-906cc5d9ebf6
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: float
        defaultValue: ""
        description: ""
        name: RATEDHP
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 045e9d8b-03bf-41a0-b149-9aed4bfcc302
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2c0deca-7f3c-404c-eee5a79a24ba
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: MOTORSIZEID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 989df53b-f180-45d5-bd75-258cca95e7d5
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 766fb95f-c4c7-46ca-a7a3-e613762ba070
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: c462a392-3dc2-468e-8cfd-38f4a6ec3fab
                stepCounter: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: 0de55244-3012-40ee-5102-40f41f2aa5f0
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLMOTORSETTINGS: eb21d3b2-f465-48b7-8a16-aaf9a30be2fe
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_XSPOC_TBLMOTORSETTINGS
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_XSPOC_TBLMOTORSETTINGS') }} "LOAD_XSPOC_TBLMOTORSETTINGS"
        name: ODS_XSPOC_TBLMOTORSETTINGS
        noLinkRefs: []
  name: ODS_XSPOC_TBLMOTORSETTINGS
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
