fileVersion: 1
id: 819ca2af-df37-3501-2cb5-bdc94ec05568
name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
operation:
  config:
    disable_hwm: false
    insertStrategy: Merge
    postSQL: ""
    preSQL: ""
    testsEnabled: false
    truncateBefore: false
  database: EDW_DEV
  deployEnabled: true
  description: ""
  isMultisource: false
  locationName: DATA_STORE
  materializationType: table
  metadata:
    appliedNodeTests: []
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b718adec-4ce3-ec72-0dd11a06a308
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: number
        defaultValue: ""
        description: ""
        isBusinessKey: true
        name: ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e35f7e9f-6f6a-4938-9dfe-ef97bb2465de
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 35ba4a26-2e21-0c23-a00a5601aba3
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config:
          is_hd: true
        dataType: varchar(50)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: a752b449-1d9f-4c1a-99be-af71243977b9
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a6650a5a-1c3e-ca21-a8d036b3dadb
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config:
          is_hd: true
        dataType: varchar(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGVIDEO
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 82f6c442-771d-4ad2-9634-4f0f9db3d256
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 744654b1-ff1f-3760-6141f86eec18
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config:
          is_hd: true
        dataType: varchar(200)
        defaultValue: ""
        description: ""
        name: FORMATSTRINGSNAPSHOT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 87ec4cd4-08ad-4570-8486-cbfc7081b79e
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46ac2f53-928c-9553-4a314dbf0b8d
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config:
          is_hd: true
        dataType: number
        defaultValue: ""
        description: ""
        name: SNAPSHOTURIHTTPAUTHENTICATION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 6293cb2e-9729-450f-a165-c71fe18ac851
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 864db73b-0e88-7634-d048cff9b76c
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: varchar(64)
        defaultValue: ""
        description: Record source.
        name: DSS_RECORD_SOURCE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: 690f40f9-9bf5-402e-9146-f0c679eb7984
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: e2e5dd61-accb-65e1-798ed5ced4bd
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Load date.
        name: DSS_LOAD_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences:
              - columnCounter: e5d38814-8eab-4f9b-9868-f01606a7346f
                stepCounter: db74a0f5-1a71-4e44-84ed-d60abb95fa66
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6c89217e-742d-a7c4-78d5e18c9b31
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: char(1)
        defaultValue: ""
        description: Flag field to identify Deleted record
        name: DSS_DELETE_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 623c299e-16d3-cf22-a44671bf57ee
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: timestamp
        defaultValue: ""
        description: Records time when record was set to Delete by the Load process
        name: DSS_DELETE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 46d7db8a-c566-99e0-8f499655e4bf
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('1900-01-01 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was started.
        name: DSS_START_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: edd5202e-d0ea-4e06-5b6d1a61e9c2
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: TIMESTAMP
        defaultValue: CAST('2999-12-31 00:00:00' AS TIMESTAMP)
        description: Datetime a business key was retired.
        name: DSS_END_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 91d9e3d8-fef2-f6e2-b22c7859468c
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: CHAR(1)
        defaultValue: "'Y'"
        description: Flag to indicate the current (latest) version of a business key.
        name: DSS_CURRENT_FLAG
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 5bfbf4ac-c17c-246a-54007c741909
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: INTEGER
        defaultValue: "1"
        description: Version number of a business key.
        name: DSS_VERSION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 56bbfdc8-ed63-06a7-b850a75a08e6
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was created in the data warehouse.
        name: DSS_CREATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 678005e7-9cf5-41cd-d309566a5711
          stepCounter: 819ca2af-df37-3501-2cb5-bdc94ec05568
        config: {}
        dataType: TIMESTAMP
        defaultValue: ""
        description: Date and time the row was updated in the data warehouse.
        name: DSS_UPDATE_TIME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        uniqueKey: false
    cteString: ""
    enabledColumnTestIDs: []
    sourceMapping:
      - aliases:
          LOAD_XSPOC_TBLCAMERACONFIGURATIONS: db74a0f5-1a71-4e44-84ed-d60abb95fa66
        customSQL:
          customSQL: ""
        dependencies:
          - locationName: WHERESCAPE_LOAD
            nodeName: LOAD_XSPOC_TBLCAMERACONFIGURATIONS
        join:
          joinCondition: |-
            FROM {{ ref('WHERESCAPE_LOAD', 'LOAD_XSPOC_TBLCAMERACONFIGURATIONS') }} "LOAD_XSPOC_TBLCAMERACONFIGURATIONS"
        name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
        noLinkRefs: []
  name: ODS_XSPOC_TBLCAMERACONFIGURATIONS
  overrideSQL: false
  schema: CLS_DATA_STORE
  sqlType: "5"
  type: sql
  version: 1
type: Node
